#+BEGIN_COMMENT
.. title: Street , City , State , Country , Continent , what's next?
.. slug: street-city-state-country-continent-whats-next
.. date: 2021-05-15 22:43:58 UTC+05:30
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT


* Street , City , State , Country , Continent , what's next?
** Introduction
From the start of life , any organism's ultimate goal is to *reproduce*.

Any organism's correct action leads to the organism reproducing.Whether it be the Amoeba , or Blue Whale .

Luckily humans took all the right actions. Here we are!

Don't you feel excited that we are here!While Musk's Starship is flying high above earth , we have hope of becoming interplanetary species.

The same feeling humans had when they moved out of Africa , colonized Asia , started  Mesopotamian Civilization, colonized America , discovered Australia , walked on antartica , stepped on the moon.

The Age of Exploration was an an period where every rich person in Europe wanted to goto distant lands.

The Age of Exploration was an period where every rich person on Earth wanted to goto distant planets.

The Age of Exploration was an period where every rich person on Milky Way wanted to goto distant galaxies.

All of them are taken by base instinct to make more of us , spread more of us , conquer more of the universe.

** Future is coming.
Whether you want or not. We are going to be interplanetary species within this century.

We have to be ready to accept that Mars may request independence from Earth within 200 years .
There might be racism between Martians and Earthians , trade conflicts between Mars and Earth.

We have to prepare ourselves for that , make laws , take decisions.We have to learn from our time on Earth , and learn.
We have to learn by first uniting people on our planet , accept it that we are same irrespective of location , culture , language etc.

*** We have to rise like a Pheonix!







